name: topotensor
channels:
  - defaults
dependencies:
  - asttokens=3.0.0=py310haa95532_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py310hc99e966_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - colorama=0.4.6=py310haa95532_0
  - decorator=5.2.1=py310haa95532_0
  - executing=2.2.1=py310haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=6.30.1=py310haa95532_0
  - jedi=0.19.2=py310haa95532_0
  - jupyter_client=8.6.3=py310haa95532_0
  - jupyter_core=5.8.1=py310haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=h83e8143_0
  - libzlib=1.3.1=h02ab6af_0
  - matplotlib-inline=0.1.7=py310haa95532_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py310h0b37514_0
  - mkl_fft=1.3.11=py310h5810407_1
  - mkl_random=1.2.8=py310h8683371_1
  - nest-asyncio=1.6.0=py310haa95532_0
  - numexpr=2.11.0=py310ha02bb35_1
  - numpy=1.26.4=py310h12f7302_1
  - numpy-base=1.26.4=py310he4e2855_1
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py310haa95532_0
  - pandas=2.3.3=py310ha5e6156_0
  - pip=25.2=pyhc872135_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - pure_eval=0.2.3=py310haa95532_0
  - python=3.10.18=h981015d_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py310haa95532_0
  - pywin32=311=py310h885b0b7_0
  - pyzmq=27.1.0=py310h7149c55_0
  - setuptools=78.1.1=py310haa95532_0
  - six=1.17.0=py310haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=py310haa95532_0
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - tk=8.6.15=hf199647_0
  - traitlets=5.14.3=py310haa95532_0
  - typing_extensions=4.15.0=py310haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.2.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - cython==3.1.4
      - debugpy==1.8.17
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - exceptiongroup==1.3.0
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - fonttools==4.60.1
      - fqdn==1.5.1
      - fsspec==2025.9.0
      - giotto-ph==0.2.4
      - giotto-tda==0.6.2
      - gudhi==3.11.0
      - h11==0.16.0
      - hopcroftkarp==1.2.5
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - igraph==0.11.9
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - lark==1.3.0
      - markupsafe==3.0.3
      - matplotlib==3.10.6
      - mistune==3.1.4
      - mpmath==1.3.0
      - narwhals==2.7.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.4.2
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - persim==0.3.8
      - pillow==11.3.0
      - platformdirs==4.4.0
      - plotly==6.3.1
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - psutil==7.1.0
      - pycparser==2.23
      - pyflagser==0.4.7
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-json-logger==4.0.0
      - pywinpty==3.0.2
      - pyyaml==6.0.3
      - referencing==0.36.2
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - ripser==0.6.12
      - rpds-py==0.27.1
      - scikit-learn==1.3.2
      - scipy==1.15.3
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.8
      - sympy==1.14.0
      - terminado==0.18.1
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tomli==2.2.1
      - torch==2.8.0
      - torchvision==0.23.0
      - tornado==6.5.2
      - types-python-dateutil==2.9.0.20250822
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.14
      - wrapt==1.17.3
prefix: C:\Users\mxs1980\AppData\Local\miniconda3\envs\topotensor
